jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: read
    steps:
      - uses: actions/checkout@v6
      - name: Run test
        run: #Run test and create allure results
      - name: Deploy Reports to GitHub Pages with History
        uses: deivydasp/allure-deployer-action@v2
        with:
          allure_results_path: 'allure-results'
