jobs:
  deploy-slack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - name: Run test
        run: # Run test and create allure results
      - name: Deploy Report and notify Slack
        uses: deivydasp/allure-deployer-action@v2
        with:
          allure_results_path: 'allure-results'
          show_history: 'true'
          retries: 5
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
