jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - name: Run test
        run: #Run test and create allure results
      - name: Deploy multi-project reports to GitHub Pages
        uses: deivydasp/allure-deployer-action@v2
        with:
          allure_results_path: 'allure-results'
          prefix: 'my-project'
          show_history: 'true'
