name: Test Actions
on:
  workflow_dispatch:
    inputs:
      show-history:
        description: 'Show history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Reports to GitHub Pages with History
        uses: deivydasp/allure-deployer-action@v2
        with:
          allure_results_path: 'allure-results'
          show_history: ${{ github.event.inputs.show-history }}
          prefix: 'examples-gh-pages'

