name: Test GitHub locally
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run'
        type: choice
        options:
          - gh
          - gh-no-backup
          - gh-multi
        default: gh
      runner:
        description: Runner to use
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        default: ubuntu-latest
      show-history:
        description: 'Show history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'
      prefix:
        description: 'Prefix'
        default: 'local-action'
      branch:
        description: 'GitHub pages deployment branch'
        default: 'gh-pages'

jobs:
  gh:
    if: ${{ github.event.inputs.job == 'gh' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Reports to GitHub Pages with History
        uses: ./
        with:
          github_pages_branch: ${{ github.event.inputs.branch }}
          prefix: ${{ github.event.inputs.prefix || '' }}
          allure_results_path: 'allure-results'
          show_history: ${{ github.event.inputs.show-history }}
          report_name: ${{ github.event.inputs.report-name }}

  gh-multi:
    if: ${{ github.event.inputs.job == 'gh-multi' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Reports to GitHub Pages 1
        uses: ./
        with:
          github_pages_branch: ${{ github.event.inputs.branch }}
          prefix: ${{ github.event.inputs.prefix || '' }}
          allure_results_path: 'allure-results'
          show_history: ${{ github.event.inputs.show-history }}
          report_name: ${{ github.event.inputs.report-name }}


      - name: Deploy Reports to GitHub Pages 2
        uses: ./
        with:
          github_pages_branch: ${{ github.event.inputs.branch }}
          prefix: ${{ github.event.inputs.prefix || '' }}
          allure_results_path: 'allure-results'
          show_history: ${{ github.event.inputs.show-history }}
          report_name: ${{ github.event.inputs.report-name }}


  gh-no-backup:
    if: ${{ github.event.inputs.job == 'gh-no-backup' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: none
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Reports to GitHub Pages (no artifact backup)
        uses: ./
        with:
          github_pages_branch: ${{ github.event.inputs.branch }}
          allure_results_path: 'allure-results'
          show_history: ${{ github.event.inputs.show-history }}
          report_name: ${{ github.event.inputs.report-name }}

